in.log, logwarn_openqa, test_logwarn
Linked to (needs to be merged first): https://github.com/os-autoinst/openQA/pull/1386
=> Ignore OpenID failed login caused by provider

in.log, logwarn_openqa, test_logwarn
https://progress.opensuse.org/issues/29289
=> Add ignore for deleted needles warning

in.log, logwarn_openqa, test_logwarn
* Add ignore for invalid input syntax (poo#29481)
* Add ignore for api_description not resolved (poo#29478)
=> Blacklist entries for poo#29418 poo#28478

pretty_logwarn
Related progress issue: https://progress.opensuse.org/issues/53435
=> Prevent sending out emails with unreadable long lines

.github/workflows/ci.yaml
Issue: https://progress.opensuse.org/issues/105828
=> Add GitHub Workflow

.github/workflows/ci.yaml, test_logwarn
Issue: https://progress.opensuse.org/issues/105828
=> Improve unit tests

in.log, logwarn_openqa, test_logwarn
Issue: https://progress.opensuse.org/issues/105918
=> Ignore "Invalid revision range"

in.log, logwarn_openqa, test_logwarn
https://progress.opensuse.org/issues/106245
=> Ignore "Testsuite ... is invalid"

README.md
Travis is no longer being used
=> Update README.md to refer to GHA badge and CI

in.log, logwarn_openqa, test_logwarn
See: https://progress.opensuse.org/issues/106613
=> Ignore "Can't update OpenQA::Schema::Result::JobLocks row not found"

README.md
The existing steps to run tests are somewhat ambiguous.
=> Clarify local test steps in README.md

in.log, logwarn_openqa, test_logwarn
Issue: https://progress.opensuse.org/issues/106759
=> Ignore "Worker has no heartbeat"

logwarn_openqa
See https://progress.opensuse.org/issues/107719
=> Add exception for `Could not render response at …`

in.log, logwarn_openqa, test_logwarn
Issue: https://progress.opensuse.org/issues/110260
=> Ignore "... is not a git directory"

in.log, logwarn_openqa, test_logwarn
Related progress issue: https://progress.opensuse.org/issues/106759
=> Remove "heartbeat" ignore which we would like to see again

.github/workflows/commit_message_checker.yml
See the worflow for the individual rules
=> CI: Add workflow for commit message checks

in.log, logwarn_openqa, test_logwarn
The problem has been fixed.
Progress: https://progress.opensuse.org/issues/110260
=> Revert "Ignore "... is not a git directory""

in.log, logwarn_openqa, test_logwarn
See: https://progress.opensuse.org/issues/113030
=> Ignore "ambiguous argument '(unreadable git hash).."

logwarn_openqa, test_logwarn
See: https://progress.opensuse.org/issues/178147
=> Ignore errors related to comments on jobs

in.log, logwarn_openqa, test_logwarn
More information was added inside of the parentheses
=> Adjust regex for RabbitMQ messages

in.log, logwarn_openqa, test_logwarn
* Remove exception after https://github.com/os-autoinst/openQA/pull/6308 has been merged
* See https://progress.opensuse.org/issues/178147
=> Remove exception for connection failure on AMQP publishing

in.log, logwarn_openqa, test_logwarn
* Remove exception after https://github.com/os-autoinst/openQA/pull/6308 has been merged
* See https://progress.opensuse.org/issues/105903
=> Remove exception for connection timeout on AMQP publishing

in.log, logwarn_openqa, test_logwarn
Related progress issue: https://progress.opensuse.org/issues/183302
=> Ignore recoverable database connection errors (poo#183302)
